"""
Builds tTimers' fallback job ability recast table from a PhoenixXI (or other LandSandBoat)
server checkout.

    data/partyrecasts.lua   [abilityId] = { recast seconds, recast timer id }

Party members' recasts are normally read straight from the action packet: the server fills its
recast field with the ability's real recast after merits and recast gear (LandSandBoat
src/map/entities/char_entity.cpp, CCharEntity::OnAbility). This table is only used when that
field is 0, which is the case for Blood Pacts, whose recast starts when the pact goes off.

Recasts come from sql/abilities.sql, then every .sql file in the SQL modules listed in
modules/init.txt is applied in order, the way dbtool does. On PhoenixXI that includes the era
two-hour revert (7200s) and the era job adjustments (Mug 900s, Chakra 300s, etc.).

Usage:
    python tools/build_party_recasts.py <server checkout>
"""

import os
import re
import sys

ROW = re.compile(r"^INSERT INTO `abilities` VALUES \((\d+),'([^']*)',\d+,\d+,\d+,(\d+),(\d+),")
UPDATE = re.compile(r"UPDATE\s+`?abilities`?\s+SET\s+(.+?)\s+WHERE\s+(.+?);", re.I | re.S)


def read_abilities(root):
    abilities = {}
    with open(os.path.join(root, 'sql', 'abilities.sql'), encoding='utf-8') as f:
        for line in f:
            m = ROW.match(line)
            if m:
                abilities[int(m.group(1))] = {'name': m.group(2), 'recast': int(m.group(3)), 'recastId': int(m.group(4))}
    return abilities


def module_sql_files(root):
    init = os.path.join(root, 'modules', 'init.txt')
    if not os.path.exists(init):
        return []
    files = []
    for line in open(init, encoding='utf-8'):
        entry = line.strip().rstrip('/')
        if not entry or entry.startswith('#'):
            continue
        path = os.path.join(root, 'modules', entry)
        if entry.endswith('.sql') and os.path.isfile(path):
            files.append(path)
        elif os.path.isdir(path) and re.search(r'(^|/)sql(/|$)', entry):
            files += sorted(os.path.join(path, n) for n in os.listdir(path) if n.endswith('.sql'))
    return files


def targets(where, abilities):
    """Ability ids matched by a WHERE clause: name = 'x', name IN ('x', ...), or abilityId = n."""
    where = where.replace('`', '')
    names = None
    m = re.match(r"\s*name\s*=\s*'([^']+)'\s*$", where, re.I)
    if m:
        names = {m.group(1)}
    m = re.match(r"\s*name\s+IN\s*\((.+)\)\s*$", where, re.I | re.S)
    if m:
        names = set(re.findall(r"'([^']+)'", m.group(1)))
    if names is not None:
        return [i for i, a in abilities.items() if a['name'] in names]
    m = re.match(r"\s*abilityId\s*=\s*(\d+)\s*$", where, re.I)
    if m:
        return [int(m.group(1))]
    return None


def main(root):
    abilities = read_abilities(root)
    applied, skipped = 0, []
    for path in module_sql_files(root):
        text = re.sub(r'--[^\n]*', '', open(path, encoding='utf-8-sig').read())
        for m in UPDATE.finditer(text):
            ids = targets(m.group(2), abilities)
            if ids is None:
                skipped.append(f'{os.path.relpath(path, root)}: WHERE {m.group(2).strip()[:60]}')
                continue
            for clause in m.group(1).split(','):
                key, _, value = clause.partition('=')
                key = key.strip().strip('`').lower()
                value = value.strip()
                if key in ('recasttime', 'recastid') and value.isdigit():
                    for i in ids:
                        if i in abilities:
                            abilities[i]['recast' if key == 'recasttime' else 'recastId'] = int(value)
                            applied += 1

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'partyrecasts.lua')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    rows = [f"    [{i}] = {{ {a['recast']}, {a['recastId']} }}, -- {a['name']}"
            for i, a in sorted(abilities.items()) if a['recast'] > 0]
    with open(out, 'w', encoding='utf-8') as f:
        f.write('-- Generated by tools/build_party_recasts.py from the server\'s abilities.sql plus its module SQL.\n')
        f.write('-- [abilityId] = { base recast in seconds, recast timer id }. Fallback only: the action packet\n')
        f.write('-- carries each player\'s real recast for most job abilities.\n')
        f.write('return {\n' + '\n'.join(rows) + '\n};\n')
    print(f'abilities: {len(abilities)}  with a recast: {len(rows)}  module changes applied: {applied}')
    for s in skipped:
        print('  skipped (unrecognized WHERE):', s)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    main(sys.argv[1])
