"""
Builds npcgil-phx's NPC sell-price table from a PhoenixXI (or other LandSandBoat) server checkout.

    data/prices.lua   [itemId] = base NPC sell price (npcgil-phx applies your fame, fame.lua)

Usage:
    python build_prices.py <server checkout>

How the server prices a sale (scripts/globals/shop.lua, xi.shop.onSellPriceCheck):
    price = max(1, floor(BaseSell * (priceRank + 389) / 400)), and 0 when BaseSell is 0.
    Items flagged NOSALE can't be sold to an NPC at all (packets/c2s/0x084_shop_sell_req.cpp).
    priceRank (1-21) comes from fame in the shop's area; Jeuno, Aht Urhgan, Tavnazia and shops without
    fame pricing always use rank 11, the plain BaseSell. The table stores BaseSell and fame.lua applies
    the rank for the player's fame at runtime.

BaseSell and flags come from sql/item_basic.sql, then every .sql file under the sql module folders
listed in modules/init.txt is applied the way dbtool loads them: `UPDATE item_basic SET baseSell = N`
and `flags = flags | ... @FLAG_NOSALE` (PhoenixXI's pre-RMT vendor price reverts and item fixes).
"""

import os
import re
import sys

ITEM_ROW = re.compile(r"^INSERT INTO `item_basic` VALUES \((\d+),\d+,'((?:[^'\\]|\\.)*)','(?:[^'\\]|\\.)*','(?:[^'\\]|\\.)*',[^,]+,\d+,([^,]+),[^,]+,(\d+)\);")
UPDATE = re.compile(r"UPDATE\s+`?item_basic`?\s+SET\s+(.+?)\s+WHERE\s+`?itemid`?\s*=\s*(\d+)\s*;", re.I | re.S)


def read_items(root):
    items = {}
    with open(os.path.join(root, 'sql', 'item_basic.sql'), encoding='utf-8') as f:
        for line in f:
            m = ITEM_ROW.match(line)
            if m:
                items[int(m.group(1))] = {
                    'name': m.group(2),
                    'nosale': '@FLAG_NOSALE' in m.group(3),
                    'base': int(m.group(4)),
                }
    return items


def module_sql_files(root):
    init = os.path.join(root, 'modules', 'init.txt')
    if not os.path.exists(init):
        return []
    files = []
    for line in open(init, encoding='utf-8'):
        entry = line.strip().rstrip('/')
        if not entry or entry.startswith('#'):
            continue
        path = os.path.join(root, 'modules', entry)
        if entry.endswith('.sql') and os.path.isfile(path):
            files.append(path)
        elif os.path.isdir(path) and re.search(r'(^|/)sql(/|$)', entry):
            files += sorted(os.path.join(path, n) for n in os.listdir(path) if n.endswith('.sql'))
    return files


def apply_sql(items, path, stats):
    text = open(path, encoding='utf-8-sig').read()
    text = re.sub(r'--[^\n]*', '', text)
    for m in UPDATE.finditer(text):
        item = items.get(int(m.group(2)))
        if item is None:
            continue
        for clause in re.split(r',(?![^()]*\))', m.group(1)):
            key, _, value = clause.partition('=')
            key = key.strip().strip('`').lower()
            value = value.strip()
            if key == 'basesell' and value.isdigit():
                item['base'] = int(value)
                stats['price'] += 1
            elif key == 'flags' and '@FLAG_NOSALE' in value:
                if re.search(r'&\s*~\s*@FLAG_NOSALE', value):
                    item['nosale'] = False
                elif '|' in value:
                    item['nosale'] = True
                stats['flags'] += 1


def main(root):
    items = read_items(root)
    stats = {'price': 0, 'flags': 0}
    files = module_sql_files(root)
    for path in files:
        apply_sql(items, path, stats)

    rows = []
    for item_id in sorted(items):
        item = items[item_id]
        if item['nosale'] or item['base'] <= 0:
            continue
        rows.append(f"[{item_id}]={item['base']},")

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'prices.lua')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        f.write('--Generated by tools/build_prices.py. Base NPC sell price (BaseSell) of each item; Loot Session\n')
        f.write('--applies your fame (fame.lua: BaseSell x (priceRank + 389) / 400). Items missing here can\'t be sold to an NPC.\n')
        f.write('return {\n')
        for i in range(0, len(rows), 8):
            f.write('    ' + ' '.join(rows[i:i + 8]) + '\n')
        f.write('};\n')
    print(f'items: {len(items)}  sellable: {len(rows)}  module sql files: {len(files)}  '
          f'price updates: {stats["price"]}  NOSALE flag updates: {stats["flags"]}')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    main(sys.argv[1])
